# Generated by Django 4.2.5 on 2023-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('company', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WithholdingTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_foreigner', models.BooleanField()),
                ('percentage_foreigner', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_total_incomes', models.IntegerField()),
                ('gross_voluntary_withholding', models.IntegerField()),
                ('social_security_values', models.JSONField()),
                ('food_bonus', models.IntegerField()),
                ('dependent_sum', models.IntegerField()),
                ('procedure_type', models.CharField(max_length=1)),
                ('argument_procedure_type', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payroll_date', models.DateField()),
                ('initial_date_contract', models.DateField()),
                ('final_date_contract', models.DateField()),
                ('housing_relief', models.IntegerField()),
                ('health_relief', models.IntegerField()),
                ('housing_relief_cap', models.IntegerField()),
                ('health_relief_cap', models.IntegerField()),
                ('uvt_value', models.IntegerField()),
                ('non_constitutive_incomes_cap', models.IntegerField()),
                ('minimum_month_salary', models.IntegerField()),
                ('exempt_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exempt_cap', models.IntegerField()),
                ('accumulated_exemption', models.IntegerField()),
                ('exempts_periodicity', models.CharField(max_length=1)),
                ('deductible_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductible_cap', models.IntegerField()),
                ('accumulated_deductible', models.IntegerField()),
                ('voluntary_cap_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voluntary_cap', models.IntegerField()),
                ('dependent', models.BooleanField()),
                ('dependent_cap', models.IntegerField()),
                ('dependent_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
